package db

import (
	"fmt"
	"regexp"
	"strings"
)

// StatementKind classifies a validated statement so the caller (see
// exec.go) knows whether to run it as a read query or a DDL action.
type StatementKind int

const (
	KindSelect StatementKind = iota
	KindExplain
	KindCreateIndex
	KindDropIndex
)

var leadingKeywordRe = regexp.MustCompile(`^\s*([A-Za-z]+)`)

var createIndexRe = regexp.MustCompile(`(?is)^\s*CREATE\s+INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?[A-Za-z_][A-Za-z0-9_]*\s+ON\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]+)\)\s*$`)
var dropIndexRe = regexp.MustCompile(`(?is)^\s*DROP\s+INDEX\s+(?:IF\s+EXISTS\s+)?[A-Za-z_][A-Za-z0-9_]*\s*$`)

// blockedSubstrings is defense-in-depth: none of these should ever match
// given the allowlist below already excludes them, but a second,
// independent check costs nothing and protects against a mistake in the
// allowlist logic.
var blockedSubstrings = []string{"ATTACH", "PRAGMA", "LOAD_EXTENSION", "VACUUM"}

// ValidateStatement rejects everything except a single read query
// (SELECT / EXPLAIN QUERY PLAN) or a single CREATE/DROP INDEX targeting a
// known demo table and column, whether the statement was typed by a
// visitor or generated by the in-browser AI — both are equally untrusted
// input from the server's point of view.
func ValidateStatement(stmt string) (StatementKind, string, error) {
	trimmed := strings.TrimSpace(stmt)
	if trimmed == "" {
		return 0, "", fmt.Errorf("empty statement")
	}

	// Allow exactly one optional trailing semicolon, then reject anything
	// containing another — blocks stacked statements.
	trimmed = strings.TrimSuffix(trimmed, ";")
	if strings.Contains(trimmed, ";") {
		return 0, "", fmt.Errorf("only a single statement is allowed")
	}

	upper := strings.ToUpper(trimmed)
	for _, bad := range blockedSubstrings {
		if strings.Contains(upper, bad) {
			return 0, "", fmt.Errorf("%q is not allowed in this sandbox", bad)
		}
	}

	m := leadingKeywordRe.FindStringSubmatch(trimmed)
	if m == nil {
		return 0, "", fmt.Errorf("could not determine statement type")
	}
	lead := strings.ToUpper(m[1])

	switch lead {
	case "SELECT":
		return KindSelect, trimmed, nil
	case "EXPLAIN":
		if !strings.HasPrefix(upper, "EXPLAIN QUERY PLAN") {
			return 0, "", fmt.Errorf("only EXPLAIN QUERY PLAN is allowed, not raw EXPLAIN")
		}
		return KindExplain, trimmed, nil
	case "CREATE":
		table, columns, err := parseIndexTarget(createIndexRe, trimmed)
		if err != nil {
			return 0, "", err
		}
		if err := validateColumns(table, columns); err != nil {
			return 0, "", err
		}
		return KindCreateIndex, trimmed, nil
	case "DROP":
		if !dropIndexRe.MatchString(trimmed) {
			return 0, "", fmt.Errorf("DROP is only allowed as DROP INDEX [IF EXISTS] <name>")
		}
		return KindDropIndex, trimmed, nil
	default:
		return 0, "", fmt.Errorf("statement type %q is not allowed in this sandbox (allowed: SELECT, EXPLAIN QUERY PLAN, CREATE INDEX, DROP INDEX)", lead)
	}
}

func parseIndexTarget(re *regexp.Regexp, stmt string) (table string, columns []string, err error) {
	m := re.FindStringSubmatch(stmt)
	if m == nil {
		return "", nil, fmt.Errorf("CREATE is only allowed as CREATE INDEX <name> ON <table>(<columns>)")
	}
	table = strings.ToLower(m[1])
	for _, c := range strings.Split(m[2], ",") {
		c = strings.ToLower(strings.TrimSpace(c))
		// Strip a trailing ASC/DESC modifier, if present.
		c = strings.TrimSpace(strings.TrimSuffix(strings.TrimSuffix(c, " desc"), " asc"))
		columns = append(columns, c)
	}
	return table, columns, nil
}

func validateColumns(table string, columns []string) error {
	allowed, ok := AllowedColumns[table]
	if !ok {
		return fmt.Errorf("unknown table %q", table)
	}
	if len(columns) == 0 {
		return fmt.Errorf("index must reference at least one column")
	}
	for _, c := range columns {
		if !allowed[c] {
			return fmt.Errorf("column %q is not a valid column on %q", c, table)
		}
	}
	return nil
}
